const index = {
  colors: {
    primary: '#06B2FD',
    primary_light: '#3F7EB4',
    secondary: '#15306E',
    tertiary: '#FFBB12',
    alert: '#E74C3C',
    success: '#1BB55C',
    icon: '#979797',
    blue_light: '#EEF2FA',
    background: '#EEF2FA',
    background_page: '#fff',
    grey: '#4F4F4F',
    background_grey: '#C5C5C5',
    text: '#333333',
    text_light: '#979797',
    text_shape: '#FFFFFF',
    text_link: '#159BFE',
    text_button_dark: '#151517',
    text_dark: '#000000',
    text_blue: '#84A6C6',
    text_collapsable: '#1F2C37',
    border: '#CBCBCB',
    divider: '#ECECEC',
    border_select: '#ECEDF3',
    gray_light: 'rgba(151,151,151,0.06)',
    picker_border_color: 'rgba(38, 50, 56, 0.38)',
    paper: '#FFFFFF',
    background_info: '#dde6f7',
    orange: '#FFBB12',
    alertColors: {
      success: '#1BB55C',
      warning: 'rgba(245, 165, 8, 0.1)',
      danger: '#EECECF',
      info: '#EEF2FA',
      icon_warning: '#F8C205',
      icon_info: '#2E5AAC',
      text_success: '#fff',
      text_warning: '',
      text_danger: '',
    },
    dark_opacity: 'rgba(0, 0, 0, 0.51)',
  },
  fonts: {
    regular: 'Inter_400Regular',
    medium: 'Inter_500Medium',
    semi_bold: 'Inter_600SemiBold',
    bold: 'Inter_700Bold',
    secondary_regular: 'RedHatText_400Regular',
    secondary_medium: 'RedHatText_500Medium',

    secondary_bold: 'RedHatText_700Bold',
  },
  shape: {
    lateral_spacing: 20,
    default_border_radius: 20,
    padding_bottom_sheet_container: 20,
    border_default: 8,
    border_top_left_radius: 20,
    border_top_right_radius: 20,
    border_width_bottom: 2,
    border_radius_select: 6,
    border_whidth_select: 0.5,
    padding_vertical_select: 12,
    padding_horizontal_select: 12,
    margin_top_select: 10,
    margin_end_select: 10,
    height_input_select: 58,
    width_input_select: 100,
    width_container_select: 100,
    border_radius_card: 10,
    border_radius_spotlight: 2,
    border_radius_status_flag: 10,
    width_container_spotlight: 6,
    height_divider: 2,
    margin_card: 16,
    margin_flag: 6,
    width_flag: 20,
    margin_left_icon_card: 4,
    pading_icon_card: 2,
    width_checkBox: 16,
    height_checkBox: 16,
    border_radius_checkBox: 1,
    border_width_checkBox: 1,
    border_radius: 5,
    border_radius_progress: 10,
    width_progress: 100,
    min_width_progress: 1,
    max_width_progress: 90,
    margin_top_container_progress: 10,
    margin_bottom_icon_progress: 13,
    height_progress: 10,
    padding_content_modal: 6,
    padding_container_modal: 12,
    width_modal_container: 80,
    max_height_modal_container: 90,
    border_radius_container_modal: 5,
    width_button_modal: 8,
    height_button_modal: 8,
  },
  spacings: {
    none: 0,
    tn: 4,
    xsm: 6,
    sm: 8,
    md: 12,
    lg: 14,
    xlg: 16,
    hg: 20,
    ms: 24,
    xxxs: 39,
  },

  shadows: {},
  typography: {
    title: 34,
    titleButton: 19,
    titleHeader: 18,
    subtitle: 24,
    paragraph: 16,
    label: 14,
    labelSmall: 12,
    labelBold: 14,
    labelSelect: 30,
  },
};
export default index;
